export default {
    API: {
        DATA_REQUEST: "API/DATA_REQUEST",
        DATA_SUCCESS: "API/DATA_SUCCESS",
        DATA_FAILED: "API/DATA_FAILED",

        PLAYERS_SUCCESS: "API/PLAYERS_SUCCESS",
        HEROES_SUCCESS: "API/HEROES_SUCCESS",
        POOL_SUCCESS: "API/POOL_SUCCESS"
    },

    DRAFT: {
        SELECT_HERO: "DRAFT/SELECT_HERO",
        UNSELECT_HERO: "DRAFT/UNSELECT_HERO"
    }
};
