export default {
    API: {
        DATA_REQUEST: "API/DATA_REQUEST",
        DATA_SUCCESS: "API/DATA_SUCCESS",
        DATA_FAILED: "API/DATA_FAILED",

        PLAYERS_SUCCESS: "API/PLAYERS_SUCCESS",
        HEROES_SUCCESS: "API/HEROES_SUCCESS",
        POOL_SUCCESS: "API/POOL_SUCCESS"
    }
};
